// GENERATED FILE - DO NOT MODIFY
// SEE https://github.com/usvc/go-generate-version for more information
//
// GENERATED BY GO:GENERATE AT 2019-03-18T17:22:07&#43;0800
//
// FILE GENERATED USING ~/generators/versioning/main.go

package main

// Version stores the latest git tag
const Version = "0.0.0-unset"

// Commit stores the commit SHA hash
const Commit = "97ee83f"
